[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Jonas Bushart <jonas@bushart.org>"]
# edition = "2018"

[dependencies]
aoc-runner = "0.2.0-alpha1"
aoc-runner-derive = "0.2.0-alpha1"
hashbrown = "0.1.6"
misc_utils = "2.1.0"
rayon = "1.0.3"
